version: '3.8'

services:
  postgres:
    build:
      context: ./persistance
    environment:
      POSTGRES_DB: game
      POSTGRES_USER: wizard
      POSTGRES_PASSWORD: wizardOfOZ
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/game
      SPRING_DATASOURCE_USERNAME: wizard
      SPRING_DATASOURCE_PASSWORD: wizardOfOZ
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend/pokemon
    ports:
      - "3000:3000"
    depends_on:
      - backend